language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE pgn_chess_test;'

before_script:
  - composer install --no-interaction
  - cp .env.travis .env

script:
  - php cli/db-create.php
  - php cli/db-seed.php tests/integration/data/01-games.pgn
  - vendor/bin/phpunit --configuration phpunit-travis.xml
